/* metronome.js */
let metronomeInterval=null,isPlaying=false,bpm=120,lastTap=0,audioCtx;
function updateBPM(){const sl=document.getElementById('bpm-slider'),ds=document.getElementById('bpm-display');if(sl)bpm=parseInt(sl.value);if(ds)ds.textContent=bpm;if(isPlaying){stopMetronome();startMetronome();}}
function increaseBPM(){bpm=Math.min(220,bpm+5);const sl=document.getElementById('bpm-slider'),ds=document.getElementById('bpm-display');if(sl)sl.value=bpm;if(ds)ds.textContent=bpm;if(isPlaying){stopMetronome();startMetronome();}}
function decreaseBPM(){bpm=Math.max(30,bpm-5);const sl=document.getElementById('bpm-slider'),ds=document.getElementById('bpm-display');if(sl)sl.value=bpm;if(ds)ds.textContent=bpm;if(isPlaying){stopMetronome();startMetronome();}}
function playClick(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='square';o.frequency.value=1200;f.type='lowpass';f.frequency.value=1800;g.gain.value=.6;o.connect(f);f.connect(g);g.connect(audioCtx.destination);o.start();setTimeout(()=>{g.gain.linearRampToValueAtTime(.001,audioCtx.currentTime+.08);setTimeout(()=>o.stop(),120);},30);}
function startMetronome(){if(isPlaying)stopMetronome();const bb=document.getElementById('beat-bar'),btn=document.getElementById('btn-metronome');isPlaying=true;if(btn)btn.textContent='Parar';const iv=(60/bpm)*1000;playClick();if(bb)bb.classList.add('active');setTimeout(()=>{if(bb)bb.classList.remove('active');},80);metronomeInterval=setInterval(()=>{playClick();if(bb){bb.classList.add('active');setTimeout(()=>{if(bb)bb.classList.remove('active');},80);}},iv);}
function stopMetronome(){if(metronomeInterval){clearInterval(metronomeInterval);metronomeInterval=null;}isPlaying=false;const bb=document.getElementById('beat-bar'),btn=document.getElementById('btn-metronome');if(bb)bb.classList.remove('active');if(btn)btn.textContent='Iniciar';}
function toggleMetronome(){if(isPlaying)stopMetronome();else startMetronome();}
function tapTempo(){const n=Date.now(),btn=document.getElementById('btn-metronome');if(lastTap>0){const d=n-lastTap;if(d>150&&d<2000){const nb=Math.round(60000/d);bpm=Math.max(30,Math.min(220,nb));const sl=document.getElementById('bpm-slider'),ds=document.getElementById('bpm-display');if(sl)sl.value=bpm;if(ds)ds.textContent=bpm;if(isPlaying){stopMetronome();startMetronome();}window.showToast&&window.showToast(bpm+' BPM');}}lastTap=n;if(btn){btn.style.transform='scale(.9)';setTimeout(()=>{if(btn)btn.style.transform='';},80);}}
function initMetronome(){const ds=document.getElementById('bpm-display'),sl=document.getElementById('bpm-slider');if(ds)ds.textContent=bpm;if(sl){sl.value=bpm;sl.addEventListener('input',updateBPM);}}
window.updateBPM=updateBPM;window.increaseBPM=increaseBPM;window.decreaseBPM=decreaseBPM;window.toggleMetronome=toggleMetronome;window.tapTempo=tapTempo;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initMetronome);else initMetronome();
