/* scales.js */
const scales=[{id:'c-major',name:'Dó Maior',type:'Maior',positions:[0,1,0,2,3,0],notes:['C','D','E','F','G','A','B'],free:true},{id:'a-minor',name:'Lá Menor',type:'Menor Natural',positions:[0,1,2,2,0,0],notes:['A','B','C','D','E','F','G'],free:true},{id:'g-major',name:'Sol Maior',type:'Maior',positions:[3,2,0,0,0,3],notes:['G','A','B','C','D','E','F#'],free:true},{id:'e-minor',name:'Mi Menor',type:'Menor Natural',positions:[0,2,2,0,0,0],notes:['E','F#','G','A','B','C','D'],free:true},{id:'d-major',name:'Ré Maior',type:'Maior',positions:[null,0,0,2,3,2],notes:['D','E','F#','G','A','B','C#'],free:true},{id:'c-minor',name:'Dó Menor',type:'Menor Natural',positions:[0,1,3,3,2,0],notes:['C','D','Eb','F','G','Ab','Bb'],free:false},{id:'pentatonic',name:'Pentatônica Lá',type:'Pentatônica',positions:[0,3,5,2,0,0],notes:['A','C','D','E','G'],free:false},{id:'blues',name:'Blues em Mi',type:'Blues',positions:[0,3,0,2,3,0],notes:['E','G','A','Bb','B','D'],free:false}];
function drawScaleDiagram(pos,cont){cont.innerHTML='';const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('width','140');s.setAttribute('height','130');s.setAttribute('viewBox','0 0 140 130');const bg=document.createElementNS('http://www.w3.org/2000/svg','rect');bg.setAttribute('x','0');bg.setAttribute('y','0');bg.setAttribute('width','140');bg.setAttribute('height','130');bg.setAttribute('fill','#2C2118');s.appendChild(bg);const nut=document.createElementNS('http://www.w3.org/2000/svg','rect');nut.setAttribute('x','18');nut.setAttribute('y','12');nut.setAttribute('width','104');nut.setAttribute('height','7');nut.setAttribute('fill','#D4AF37');s.appendChild(nut);for(let i=0;i<4;i++){const y=24+i*22;const f=document.createElementNS('http://www.w3.org/2000/svg','line');f.setAttribute('x1','18');f.setAttribute('y1',y);f.setAttribute('x2','122');f.setAttribute('y2',y);f.setAttribute('stroke','#8B5A2B');f.setAttribute('stroke-width','2');s.appendChild(f);}for(let i=0;i<6;i++){const x=22+i*18;const st=document.createElementNS('http://www.w3.org/2000/svg','line');st.setAttribute('x1',x);st.setAttribute('y1','12');st.setAttribute('x2',x);st.setAttribute('y2','120');st.setAttribute('stroke','#F5E8C7');st.setAttribute('stroke-width','1.1');s.appendChild(st);}pos.forEach((p,str)=>{const x=22+str*18;if(p===0){const o=document.createElementNS('http://www.w3.org/2000/svg','circle');o.setAttribute('cx',x);o.setAttribute('cy','8');o.setAttribute('r','4');o.setAttribute('fill','#00D4FF');s.appendChild(o);}else if(p!==null){const y=24+p*22-11;const d=document.createElementNS('http://www.w3.org/2000/svg','circle');d.setAttribute('cx',x);d.setAttribute('cy',y);d.setAttribute('r','6');d.setAttribute('fill','#00D4FF');s.appendChild(d);const n=document.createElementNS('http://www.w3.org/2000/svg','text');n.setAttribute('x',x);n.setAttribute('y',y+3);n.setAttribute('text-anchor','middle');n.setAttribute('fill','#2C2118');n.setAttribute('font-size','8');n.setAttribute('font-weight','700');n.textContent=p;s.appendChild(n);}});cont.appendChild(s);}
function playScaleSound(sc){try{const ac=new(window.AudioContext||window.webkitAudioContext)();const ns=sc.notes||['C','D','E','F','G'];ns.forEach((n,i)=>{setTimeout(()=>{const o=ac.createOscillator(),g=ac.createGain(),f=ac.createBiquadFilter();const nf={'C':261.6,'C#':277.2,'D':293.7,'D#':311.1,'E':329.6,'F':349.2,'F#':370,'G':392,'G#':415.3,'A':440,'A#':466.2,'B':493.9,'Bb':466.2,'Eb':311.1,'Ab':415.3};const fr=nf[n]||300;o.type='sine';o.frequency.value=fr;f.type='lowpass';f.frequency.value=1800;g.gain.value=.25;o.connect(f);f.connect(g);g.connect(ac.destination);o.start();setTimeout(()=>{g.gain.linearRampToValueAtTime(.001,ac.currentTime+.35);setTimeout(()=>o.stop(),400);},280);},i*180);});}catch(e){}}
function renderScaleCard(sc){const un=sc.free||localStorage.getItem('cifras_premium')==='true';const c=document.createElement('div');c.className='chord-card'+(!un?' premium-locked':'');c.innerHTML=`<div class="chord-name">${sc.name}</div><div class="chord-type">${sc.type}</div>`+(!un?'<div style="font-size:.65rem;color:#D4AF37;margin-top:3px;">🔒 Premium</div>':'');const d=document.createElement('div');d.style.marginTop='6px';drawScaleDiagram(sc.positions,d);c.appendChild(d);c.onclick=()=>{if(!un){if(confirm('Premium?'))window.navigateTo('premium');return;}showScaleModal(sc);};return c;}
function showScaleModal(sc){const m=document.getElementById('modal'),t=document.getElementById('modal-title'),di=document.getElementById('modal-diagram'),inf=document.getElementById('modal-info'),pb=document.getElementById('modal-play-btn'),fb=document.getElementById('modal-favorite-btn');t.textContent=sc.name;di.innerHTML='';drawScaleDiagram(sc.positions,di);inf.innerHTML=`<strong>Notas:</strong> ${sc.notes.join(' - ')}<br><strong>Tipo:</strong> ${sc.type}`;pb.onclick=()=>playScaleSound(sc);fb.onclick=()=>toggleScaleFavorite(sc);const isf=isScaleFavorite(sc);fb.textContent=isf?'★ Remover':'⭐ Favoritar';m.classList.add('active');m.style.display='flex';}
function isScaleFavorite(sc){return JSON.parse(localStorage.getItem('cifras_favorites')||'[]').some(f=>f.id===sc.id);}
function toggleScaleFavorite(sc){let f=JSON.parse(localStorage.getItem('cifras_favorites')||'[]');const i=f.findIndex(x=>x.id===sc.id);if(i>-1){f.splice(i,1);window.showToast('Removido');}else{f.push({...sc,type:'scale'});window.showToast('Favoritado ⭐');}localStorage.setItem('cifras_favorites',JSON.stringify(f));const fb=document.getElementById('modal-favorite-btn');if(fb)fb.textContent=isScaleFavorite(sc)?'★ Remover':'⭐ Favoritar';if(window.renderFavorites)window.renderFavorites();}
function filterScales(){const s=(document.getElementById('scale-search')||{}).value||'';const g=document.getElementById('scale-grid');if(!g)return;g.innerHTML='';let fl=scales;if(s.trim())fl=fl.filter(x=>x.name.toLowerCase().includes(s.toLowerCase())||x.type.toLowerCase().includes(s.toLowerCase()));fl.forEach(x=>g.appendChild(renderScaleCard(x)));}
function refreshScales(){const g=document.getElementById('scale-grid');if(!g)return;g.innerHTML='';scales.forEach(s=>g.appendChild(renderScaleCard(s)));}
function loadScales(){refreshScales();}
window.loadScales=loadScales;window.refreshScales=refreshScales;window.filterScales=filterScales;window.showScaleModal=showScaleModal;window.playScaleSound=playScaleSound;
