/* tuner.js */
let audioContext, analyser, microphone, isTuning=false, rafId;
const NOTE_STRINGS = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"], A4=440;
function noteFromPitch(f){return Math.round(12*(Math.log(f/A4)/Math.log(2)))+69;}
function frequencyFromNoteNumber(n){return A4*Math.pow(2,(n-69)/12);}
function centsOffFromPitch(f,n){return Math.floor(1200*Math.log(f/frequencyFromNoteNumber(n))/Math.log(2));}
function autoCorrelate(buf,sr){let SIZE=buf.length,rms=0;for(let i=0;i<SIZE;i++)rms+=buf[i]*buf[i];rms=Math.sqrt(rms/SIZE);if(rms<0.01)return -1;let r1=0,r2=SIZE-1,th=0.2;for(let i=0;i<SIZE/2;i++)if(Math.abs(buf[i])<th){r1=i;break;}for(let i=1;i<SIZE/2;i++)if(Math.abs(buf[SIZE-i])<th){r2=SIZE-i;break;}buf=buf.slice(r1,r2);SIZE=buf.length;let c=new Array(SIZE).fill(0);for(let i=0;i<SIZE;i++)for(let j=0;j<SIZE-i;j++)c[i]+=buf[j]*buf[j+i];let d=0;while(c[d]>c[d+1])d++;let mv=-1,mp=-1;for(let i=d;i<SIZE;i++)if(c[i]>mv){mv=c[i];mp=i;}let T0=mp;const x1=c[T0-1],x2=c[T0],x3=c[T0+1];const a=(x1+x3-2*x2)/2,b=(x3-x1)/2;if(a)T0=T0-b/(2*a);return sr/T0;}
function updateTunerDisplay(pitch){const note=document.getElementById('note-display'),cents=document.getElementById('cents-display'),fill=document.getElementById('tuner-fill'),freq=document.getElementById('freq-display');if(!note||!pitch||pitch<50){if(note)note.textContent='--';if(cents)cents.textContent='0 cents';if(fill)fill.style.width='50%';if(freq)freq.textContent='Frequência: -- Hz';return;}const nn=noteFromPitch(pitch),nm=NOTE_STRINGS[nn%12],c=centsOffFromPitch(pitch,nn);if(note)note.textContent=nm;if(cents)cents.textContent=c+' cents';if(freq)freq.textContent='Frequência: '+pitch.toFixed(1)+' Hz';const pct=Math.max(0,Math.min(100,50+(c/1.6)));if(fill)fill.style.width=pct+'%';}
async function startTuner(){const sb=document.getElementById('btn-start-tuner'),stp=document.getElementById('btn-stop-tuner');try{if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();const stream=await navigator.mediaDevices.getUserMedia({audio:true});microphone=audioContext.createMediaStreamSource(stream);analyser=audioContext.createAnalyser();analyser.fftSize=2048;const bl=analyser.fftSize,da=new Float32Array(bl);microphone.connect(analyser);isTuning=true;if(sb)sb.style.display='none';if(stp)stp.style.display='inline-block';function upd(){if(!isTuning)return;analyser.getFloatTimeDomainData(da);const p=autoCorrelate(da,audioContext.sampleRate);updateTunerDisplay(p);rafId=requestAnimationFrame(upd);}upd();window.showToast&&window.showToast('Microfone ativado. Toque uma corda!');}catch(e){alert('Erro microfone. Verifique permissões.');if(sb)sb.style.display='inline-block';if(stp)stp.style.display='none';}}
function stopTuner(){isTuning=false;if(rafId)cancelAnimationFrame(rafId);if(microphone)microphone.disconnect(),microphone=null;const sb=document.getElementById('btn-start-tuner'),stp=document.getElementById('btn-stop-tuner');if(sb)sb.style.display='inline-block';if(stp)stp.style.display='none';const n=document.getElementById('note-display'),c=document.getElementById('cents-display'),f=document.getElementById('tuner-fill'),fr=document.getElementById('freq-display');if(n)n.textContent='--';if(c)c.textContent='0 cents';if(f)f.style.width='50%';if(fr)fr.textContent='Frequência: -- Hz';window.showToast&&window.showToast('Afinador parado.');}
window.startTuner=startTuner;window.stopTuner=stopTuner;
